### ISSUE TITLE
COCO detection results based on ResNet-18

### ISSUE THREAD

**Issue by Rene-SP** [haohang96/bingo#3]
Hello, I notice the implementation of ResNet-18 with MaskRCNN in Detectron2 is quite different. The final stage of ResNet-18 is modified into a BottleNeck structure. In this case, the pre-trained weight can not fit to it. I wonder did you change the code of Detectron2 or just fine-tune the newly initialized BottleNeck?

**Comment by haohang96** [comment]
Yes. In the implementation of ResNet-18 with MaskRCNN-C4 in Detectron2, the final stage is modified into Bottleneck at class Res5ROIHeads(ROIHeads). In Table 3 and Table 4 of BINGO, we use ResNet-18 with MaskRCNN-FPN to avoid this problem. 

Note that in Table 3 and Table 4 of BINGO, both MoCo v2 baseline and our results are fine-tuned with the same MaskRCNN-FPN structure, which ensures the comparison is fair.

**Comment by Rene-SP** [comment]
Thanks for your rapid reply, which addresses my problem.
